"""Generate sdk/include/pascalpatch/melee_states.h: action state names for every fighter.

Reads the motion state enums of a doldecomp/melee checkout (src/melee/ft/kinds/*/forward.h)
and writes one C table for the common states (0..340) and one per fighter for its own
states (341 and up), so plugins can say "AttackAirN" instead of 65.

    python tooling/native/gen_melee_tables.py --decomp C:/path/to/melee-decomp
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "sdk/include/pascalpatch/melee_states.h"

# FighterKind order (ft/forward.h) -> the kinds/ folder holding that fighter's enum
KINDS = ["Mario", "Fox", "Captain", "Donkey", "Kirby", "Koopa", "Link", "Seak", "Ness", "Peach", "Popo", "Nana",
         "Pikachu", "Samus", "Yoshi", "Purin", "Mewtwo", "Luigi", "Mars", "Zelda", "CLink", "DrMario", "Falco",
         "Pichu", "GameWatch", "Ganon", "Emblem", "MasterHand", "CrazyHand", "ZakoBoy", "ZakoGirl", "GigaKoopa",
         "Sandbag"]
# clones have no enum of their own: they run their original's states
CLONES = {"Nana": "Popo", "CLink": "Link", "DrMario": "Mario", "Falco": "Fox", "Pichu": "Pikachu",
          "Ganon": "Captain", "Emblem": "Mars", "CrazyHand": "MasterHand", "GigaKoopa": "Koopa"}


def enum_names(text, enum):
    """The names of ``typedef enum <enum> { ... }``, in order, starting from its first value."""
    m = re.search(r"typedef\s+enum\s+" + re.escape(enum) + r"\s*\{(.*?)\}", text, re.S)
    if not m:
        return None
    body = re.sub(r"//[^\n]*|/\*.*?\*/", "", m.group(1), flags=re.S)
    names = []
    for item in body.split(","):
        item = item.strip()
        if not item:
            continue
        name, _, value = item.partition("=")
        name, value = name.strip(), value.strip()
        if names and value:
            if re.search(r"Count|Max", name):   # trailing counts and aliases end the states
                break
            raise ValueError(f"{enum}: {name} = {value} breaks the sequence")
        names.append(name)
    return names


def short(name):
    """ftCo_MS_AttackAirN -> AttackAirN"""
    return re.sub(r"^ft[A-Za-z0-9]*_MS_", "", name)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--decomp", required=True)
    a = ap.parse_args(argv)
    kinds = Path(a.decomp) / "src/melee/ft/kinds"
    common = enum_names((kinds / "ftCommon/forward.h").read_text(encoding="utf-8"), "ftCommon_MotionState")
    assert common[0] == "ftCo_MS_None" and common[-1] == "ftCo_MS_Count", common[-1]
    common = [short(n) for n in common[1:-1]]          # 0 .. Count-1
    assert common[14] == "Wait", common[14]
    lines = ["/* Generated by tooling/native/gen_melee_tables.py from the doldecomp/melee motion state",
             " * enums. Do not edit. Action state (Fighter +0x10) names: the common states are shared by",
             " * every fighter; each fighter's own states (specials, and so on) start at PP_STATE_COMMON. */",
             "#ifndef PASCALPATCH_MELEE_STATES_H", "#define PASCALPATCH_MELEE_STATES_H", "",
             f"#define PP_STATE_COMMON {len(common)}u", "",
             "static const char *const pp_common_states[PP_STATE_COMMON] = {"]
    lines += [f'    "{n}",' for n in common] + ["};", ""]
    tables = []
    for i, kind in enumerate(KINDS):
        f = kinds / f"ft{CLONES.get(kind, kind)}" / "forward.h"
        text = f.read_text(encoding="utf-8") if f.is_file() else ""
        m = re.search(r"typedef\s+enum\s+(\w+_MotionState)\s*\{", text)
        names = enum_names(text, m.group(1)) if m else None
        if names and "ftCo_MS_Count" in text.split(names[0], 1)[1].split(",", 1)[0]:
            names = [short(n) for n in names if not n.endswith("_Count") and not n.endswith("_MS_Max")]
            table = f"pp_states_{CLONES.get(kind, kind)}"
            if kind not in CLONES:
                lines.append(f"static const char *const {table}[] = {{")
                lines += [f'    "{n}",' for n in names] + ["};", ""]
            tables.append((table, len(names)))
        else:
            tables.append(("0", 0))
    lines.append("/* Indexed by FighterKind (Fighter +0x4). */")
    lines.append("static const struct { const char *const *names; unsigned count; } pp_fighter_states[] = {")
    lines += [f"    {{{t}, {n}u}},  /* {KINDS[i]} */" for i, (t, n) in enumerate(tables)] + ["};", ""]
    lines += ["/* The name of action state `state` for a fighter of kind `kind`, or 0 when unknown. */",
              "static inline const char *pp_state_name(unsigned kind, unsigned state) {",
              "    if (state < PP_STATE_COMMON) return pp_common_states[state];",
              "    if (kind >= sizeof pp_fighter_states / sizeof pp_fighter_states[0]) return 0;",
              "    state -= PP_STATE_COMMON;",
              "    return state < pp_fighter_states[kind].count ? pp_fighter_states[kind].names[state] : 0;",
              "}", "", "#endif", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT}: {len(common)} common states, {sum(n for _, n in tables)} fighter states")


if __name__ == "__main__":
    main()
