from __future__ import annotations
import re
from pathlib import Path


class FighterLoaderError(ValueError):
    pass


FIGHTER_CODES = {
    "bowser": "Bo", "captain-falcon": "Ca", "donkey-kong": "Dk", "dr-mario": "Dr",
    "falco": "Fc", "fox": "Fx", "ganondorf": "Gn", "mr-game-and-watch": "Gw",
    "ice-climbers": "Nn", "jigglypuff": "Pr", "kirby": "Kb", "link": "Lk",
    "luigi": "Lg", "mario": "Mr", "marth": "Ms", "mewtwo": "Mt", "ness": "Ns",
    "peach": "Pe", "pichu": "Pp", "pikachu": "Pk", "roy": "Fe", "samus": "Ss",
    "sheik": "Sk", "yoshi": "Ys", "young-link": "Cl", "zelda": "Zd",
}

SYMBOL_PATTERN = re.compile(r"^ftData[A-Za-z0-9]{1,32}$")
OBSERVATION_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]{1,63}$")
ENTRYPOINT_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def symbol_for_character_id(character_id):
    slug = re.sub(r"[^A-Za-z0-9]", "", str(character_id))
    if not slug or not re.match(r"^[A-Za-z0-9]+$", slug):
        raise FighterLoaderError("character id must contain an ASCII letter or digit")
    return "ftData" + slug[0].upper() + slug[1:]


def validate_fighter_symbol(symbol):
    if not isinstance(symbol, str) or not SYMBOL_PATTERN.fullmatch(symbol):
        raise FighterLoaderError(f"invalid fighter symbol: {symbol!r}")
    return symbol


def validate_observation_marker(marker):
    if not isinstance(marker, str) or not OBSERVATION_PATTERN.fullmatch(marker):
        raise FighterLoaderError(f"invalid observation marker: {marker!r}")
    return marker


def clone_slot_basename(base_fighter):
    key = str(base_fighter).strip().lower()
    code = FIGHTER_CODES.get(key)
    if code is None:
        raise FighterLoaderError(f"unknown base fighter: {base_fighter!r}")
    return f"Pl{code}.dat"


def find_clone_slot(iso_files, base_fighter):
    wanted = clone_slot_basename(base_fighter)
    exact = [entry["path"] for entry in iso_files
             if entry["path"].split("/")[-1] == wanted]
    if len(exact) == 1:
        return exact[0]
    lowered = [entry["path"] for entry in iso_files
               if entry["path"].split("/")[-1].lower() == wanted.lower()]
    if len(lowered) == 1:
        return lowered[0]
    candidates = exact or lowered
    if not candidates:
        raise FighterLoaderError(f"clone slot file {wanted} not found in ISO")
    raise FighterLoaderError(f"ambiguous clone slot file {wanted}: {sorted(candidates)}")


def fighter_loader_plugin_source(symbol, observation=None, entrypoint="meleemod_fighter_loader_init"):
    validate_fighter_symbol(symbol)
    if not isinstance(entrypoint, str) or not ENTRYPOINT_PATTERN.fullmatch(entrypoint):
        raise FighterLoaderError(f"invalid entrypoint: {entrypoint!r}")
    lines = [
        "/* Generated by MeleeMod. Do not edit. */",
        f"void {entrypoint}(void)",
        "{",
        f'    OSReport("[meleemod] fighter-load {symbol}\\n");',
    ]
    if observation is not None:
        validate_observation_marker(observation)
        lines.append(f'    OSReport("[meleemod] observation {observation}\\n");')
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_fighter_loader_plugin(symbol, dest_dir, observation=None,
                                entrypoint="meleemod_fighter_loader_init",
                                filename="fighter_loader.c"):
    source = fighter_loader_plugin_source(symbol, observation, entrypoint)
    dest = Path(dest_dir).expanduser().resolve()
    if Path(filename).is_absolute() or ".." in Path(filename).parts or len(Path(filename).parts) != 1:
        raise FighterLoaderError(f"invalid plugin filename: {filename!r}")
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / filename
    target.write_text(source, encoding="utf-8")
    return target
