from __future__ import annotations
from dataclasses import dataclass
import hashlib, os, re, shutil, subprocess, tempfile
from pathlib import Path
from .errors import CompositionError, ValidationError

IDENT=re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MARKER="/* MELEEMOD GENERATED STATIC BUNDLE */"
@dataclass(frozen=True)
class StaticBuildResult:
    dol:Path; sha1:str; clean_sha1:str|None; worktree:Path|None

def _sha1(path):
 h=hashlib.sha1();
 with Path(path).open("rb") as f:
  for b in iter(lambda:f.read(8*1024*1024),b""):h.update(b)
 return h.hexdigest()

def make_bundle(plugins, source_root):
 root=Path(source_root).resolve(); seen=set(); chunks=[]; errors=[]
 for i,p in enumerate(plugins):
  ident=p.get("id",f"plugins[{i}]"); entry=p.get("entrypoint")
  if not isinstance(entry,str) or not IDENT.fullmatch(entry): errors.append(ValidationError(f"plugins[{i}].entrypoint","identifier","static entrypoint must be a C identifier"))
  source=p.get("source")
  if not isinstance(source,str) or Path(source).is_absolute() or ".." in Path(source).parts or Path(source).suffix.lower() != ".c": errors.append(ValidationError(f"plugins[{i}].source","source","must be a relative .c source path")); continue
  path=(root/source).resolve()
  if root not in path.parents or not path.is_file(): errors.append(ValidationError(f"plugins[{i}].source","missing","plugin source does not exist below source_root")); continue
  if ident in seen: errors.append(ValidationError(f"plugins[{i}].id","duplicate","duplicate plugin ID"))
  seen.add(ident); chunks.append((ident,entry,path.read_text(encoding="utf-8")))
 if errors: raise CompositionError("invalid static plugin sources",errors)
 body=["/* Generated by MeleeMod. Do not edit. */"]
 for ident,entry,source in chunks:
  body.extend([f"/* plugin: {ident} */",source])
 body.append("void mm_meleemod_static_init(void) {")
 for ident,entry,source in chunks: body.append(f"    {entry}();")
 body.append("}")
 return "\n".join(body)+"\n"

def apply_overlay(worktree,plugins,source_root):
 tree=Path(worktree); gm=tree/"src/melee/gm/gmmain.c"; bundle=tree/"src/melee/gm/meleemod_static_bundle.c"
 if not gm.is_file(): raise CompositionError(f"known hook source is missing: {gm}")
 text=gm.read_text(encoding="utf-8")
 if MARKER in text: raise CompositionError("generated static bundle marker already exists")
 bundle.write_text(make_bundle(plugins,source_root),encoding="utf-8")
 needle="int main(void)\n{"
 if needle not in text: raise CompositionError("known main hook signature not found")
 replacement=MARKER+"\n#include \"meleemod_static_bundle.c\"\n\n"+needle
 text=text.replace(needle,replacement,1)
 # CodeWarrior uses C89-style declarations, so call after the two existing locals.
 decl="    u32 _[2];"
 if decl not in text: raise CompositionError("known main declarations not found")
 text=text.replace(decl,decl+"\n    mm_meleemod_static_init();",1)
 gm.write_text(text,encoding="utf-8")
 return bundle

def build_in_worktree(repo,base_orig,plugins,output,source_root=None,python="python",ninja="ninja"):
 repo=Path(repo).resolve(); base_orig=Path(base_orig).resolve(); output=Path(output).resolve(); output.parent.mkdir(parents=True,exist_ok=True)
 if base_orig.name == "GALE01" and (base_orig/"sys").is_dir(): base_orig=base_orig.parent
 if not (repo/".git").exists(): raise CompositionError("decompilation repository is not a Git checkout")
 if not (base_orig/"GALE01/sys").is_dir(): raise CompositionError("an extracted orig/GALE01 directory is required for static source builds")
 temp=Path(tempfile.mkdtemp(prefix="meleemod-static-")); work=temp/"repo"; builddir="build-meleemod-static"
 try:
  add=subprocess.run(["git","worktree","add","--detach",str(work),"HEAD"],cwd=repo,text=True,capture_output=True)
  if add.returncode: raise CompositionError("could not create disposable decomp worktree",[ValidationError("git","worktree",add.stderr[-2000:])])
  orig=work/"orig"
  if orig.exists() or orig.is_symlink(): shutil.rmtree(orig) if orig.is_dir() and not orig.is_symlink() else orig.unlink()
  orig.symlink_to(base_orig,target_is_directory=True)
  apply_overlay(work,plugins,Path(source_root or Path.cwd()).resolve())
  configure=[python,"configure.py","--non-matching","--build-dir",builddir]
  c=subprocess.run(configure,cwd=work,text=True,capture_output=True)
  if c.returncode: raise CompositionError("static plugin configure failed",[ValidationError("configure","failed",(c.stdout+c.stderr)[-4000:])])
  b=subprocess.run([ninja],cwd=work,text=True,capture_output=True)
  if b.returncode: raise CompositionError("static plugin build failed",[ValidationError("ninja","failed",(b.stdout+b.stderr)[-4000:])])
  dol=work/builddir/"GALE01/main.dol"
  if not dol.is_file(): raise CompositionError("static build produced no main.dol")
  shutil.copy2(dol,output); return StaticBuildResult(output,_sha1(output),None,None)
 finally:
  subprocess.run(["git","worktree","remove","--force",str(work)],cwd=repo,capture_output=True,text=True)
  shutil.rmtree(temp,ignore_errors=True)
