from __future__ import annotations
from dataclasses import dataclass
import hashlib, os, re, shutil, subprocess, tempfile
from pathlib import Path
from .errors import CompositionError, ValidationError

IDENT=re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MARKER="/* MELEEMOD GENERATED STATIC BUNDLE */"
@dataclass(frozen=True)
class StaticBuildResult:
    dol:Path; sha1:str; clean_sha1:str|None; worktree:Path|None

def _sha1(path):
 h=hashlib.sha1();
 with Path(path).open("rb") as f:
  for b in iter(lambda:f.read(8*1024*1024),b""):h.update(b)
 return h.hexdigest()

def make_bundle(plugins, source_root, runtime_root=None):
 root=Path(source_root).resolve(); runtime=Path(runtime_root).resolve() if runtime_root else None
 seen=set(); chunks=[]; signatures={}; phases={}; errors=[]
 for i,p in enumerate(plugins):
  ident=p.get("id",f"plugins[{i}]"); entry=p.get("entrypoint"); signature=p.get("static_signature","none"); phase=p.get("init_phase","first-frame")
  if not isinstance(entry,str) or not IDENT.fullmatch(entry): errors.append(ValidationError(f"plugins[{i}].entrypoint","identifier","static entrypoint must be a C identifier"))
  if signature not in {"none","context"}: errors.append(ValidationError(f"plugins[{i}].static_signature","signature",str(signature)))
  if signature=="context" and not runtime: errors.append(ValidationError(f"plugins[{i}].static_signature","runtime_required","context plugins require runtime_root"))
  if phase not in {"first-frame","startup"}: errors.append(ValidationError(f"plugins[{i}].init_phase","phase",str(phase)))
  source=p.get("source")
  if not isinstance(source,str) or Path(source).is_absolute() or ".." in Path(source).parts or Path(source).suffix.lower() != ".c":
   errors.append(ValidationError(f"plugins[{i}].source","source","must be a relative .c source path")); continue
  path=(root/source).resolve()
  if root not in path.parents or not path.is_file(): errors.append(ValidationError(f"plugins[{i}].source","missing","plugin source does not exist below source_root")); continue
  if ident in seen: errors.append(ValidationError(f"plugins[{i}].id","duplicate","duplicate plugin ID"))
  seen.add(ident); signatures[ident]=signature; phases[ident]=phase; chunks.append((ident,entry,path.read_text(encoding="utf-8")))
 if errors: raise CompositionError("invalid static plugin sources",errors)
 body=["/* Generated by MeleeMod. Do not edit. */"]
 if runtime:
  body.extend(["#include \"meleemod/runtime.h\"",(runtime/"runtime/src/events.c").read_text(encoding="utf-8"),(runtime/"runtime/src/input.c").read_text(encoding="utf-8"),(runtime/"runtime/src/ppc_runtime.c").read_text(encoding="utf-8")])
  body.append("static void mm_meleemod_runtime_init(void) { mm_runtime_init(); }")
 for ident,entry,source in chunks: body.extend([f"/* plugin: {ident} */",source])
 def emit_init(name,phase):
  body.extend([f"static int {name}_started=0;",f"static void {name}(void) {{",f"    if ({name}_started) return;",f"    {name}_started=1;"])
  for ident,entry,source in chunks:
   if phases[ident] != phase: continue
   if signatures[ident] == "context": body.extend(["    {",f"        mm_plugin_context context={{MM_PLUGIN_ABI_VERSION, \"{ident}\"}};",f"        {entry}(&context);","    }"])
   else: body.append(f"    {entry}();")
  body.append("}")
 emit_init("mm_meleemod_startup_init","startup")
 emit_init("mm_meleemod_frame_init","first-frame")
 body.append("void mm_meleemod_static_init(void) {")
 if runtime: body.append("    mm_meleemod_runtime_init();")
 body.append("    mm_meleemod_startup_init();")
 body.append("}")
 if runtime:
  body.extend(["extern HSD_PadStatus HSD_PadCopyStatus[4];", "static uint32_t mm_meleemod_frame_number=0;", "void mm_meleemod_frame(void) {", "    int i;", "    mm_event event;", "    mm_input_sample sample;", "    mm_meleemod_frame_init();", "    event.type=MM_EVENT_FRAME; event.frame=mm_meleemod_frame_number++; event.payload=0; event.payload_size=0;", "    for (i=0; i<4; i++) {", "        sample.frame=event.frame; sample.port=(uint8_t)i;", "        sample.buttons=(uint16_t)HSD_PadCopyStatus[i].button;", "        sample.stick_x=(int16_t)HSD_PadCopyStatus[i].stickX; sample.stick_y=(int16_t)HSD_PadCopyStatus[i].stickY;", "        sample.trigger_l=HSD_PadCopyStatus[i].analogL; sample.trigger_r=HSD_PadCopyStatus[i].analogR;", "        mm_input_history_push(&sample);", "    }", "    mm_dispatch(&event);", "}"])
 else: body.extend(["void mm_meleemod_frame(void) {", "    mm_meleemod_frame_init();", "}"])
 return "\n".join(body)+"\n"

def apply_overlay(worktree,plugins,source_root,runtime_root=None):
 tree=Path(worktree); gm=tree/"src/melee/gm/gmmain.c"; bundle=tree/"src/melee/gm/meleemod_static_bundle.c"; runtime=None
 if not gm.is_file(): raise CompositionError(f"known hook source is missing: {gm}")
 text=gm.read_text(encoding="utf-8")
 if MARKER in text: raise CompositionError("generated static bundle marker already exists")
 if runtime_root:
  runtime=Path(runtime_root).resolve()
  header_dest=tree/"src/meleemod"; header_dest.mkdir(parents=True,exist_ok=True)
  for header in (runtime/"runtime/include/meleemod").glob("*.h"):
   shutil.copy2(header,header_dest/header.name)
  for header in (runtime/"sdk/include/meleemod").glob("*.h"):
   shutil.copy2(header,header_dest/header.name)
 bundle.write_text(make_bundle(plugins,source_root,runtime_root),encoding="utf-8")
 needle="int main(void)\n{"
 if needle not in text: raise CompositionError("known main hook signature not found")
 replacement=MARKER+"\n#include \"meleemod_static_bundle.c\"\n\n"+needle
 text=text.replace(needle,replacement,1)
 # Initialization follows the existing startup banner, after OS and debug services are ready.
 init_call="    mm_meleemod_static_init();"
 banner_end='    OSReport("#\\n\\n");'
 if banner_end not in text: raise CompositionError("startup banner hook not found")
 text=text.replace(banner_end,banner_end+"\n"+init_call,1)
 loop=tree/"src/melee/gm/gm_1A3F.c"
 if plugins:
  loop_text=loop.read_text(encoding="utf-8")
  if MARKER in loop_text: raise CompositionError("generated frame marker already exists")
  loop_text="extern void mm_meleemod_frame(void);\n"+loop_text
  loop_needle="    while (true) {\n        u8 next_mode = "
  if loop_needle not in loop_text: raise CompositionError("known game-loop hook signature not found")
  loop_text=loop_text.replace(loop_needle,"    while (true) {\n        u8 next_mode;\n        mm_meleemod_frame();\n        next_mode =",1)
  loop.write_text(loop_text,encoding="utf-8")
 gm.write_text(text,encoding="utf-8")
 return bundle

def build_in_worktree(repo,base_orig,plugins,output,source_root=None,runtime_root=None,python="python",ninja="ninja"):
 repo=Path(repo).resolve(); base_orig=Path(base_orig).resolve(); output=Path(output).resolve(); output.parent.mkdir(parents=True,exist_ok=True)
 if base_orig.name == "GALE01" and (base_orig/"sys").is_dir(): base_orig=base_orig.parent
 if not (repo/".git").exists(): raise CompositionError("decompilation repository is not a Git checkout")
 if not (base_orig/"GALE01/sys").is_dir(): raise CompositionError("an extracted orig/GALE01 directory is required for static source builds")
 temp=Path(tempfile.mkdtemp(prefix="meleemod-static-")); work=temp/"repo"; builddir="build-meleemod-static"
 try:
  add=subprocess.run(["git","worktree","add","--detach",str(work),"HEAD"],cwd=repo,text=True,capture_output=True)
  if add.returncode: raise CompositionError("could not create disposable decomp worktree",[ValidationError("git","worktree",add.stderr[-2000:])])
  orig=work/"orig"
  if orig.exists() or orig.is_symlink(): shutil.rmtree(orig) if orig.is_dir() and not orig.is_symlink() else orig.unlink()
  orig.symlink_to(base_orig,target_is_directory=True)
  apply_overlay(work,plugins,Path(source_root or Path.cwd()).resolve(),runtime_root)
  configure=[python,"configure.py","--non-matching","--build-dir",builddir]
  tool_paths=(("--dtk",repo/"build/tools/dtk"),("--compilers",repo/"build/compilers"),("--binutils",repo/"build/binutils"),("--wrapper",repo/"build/tools/wibo"),("--sjiswrap",repo/"build/tools/sjiswrap.exe"),("--objdiff",repo/"build/tools/objdiff-cli"))
  for flag,path in tool_paths:
   if path.exists(): configure.extend([flag,str(path)])
  c=subprocess.run(configure,cwd=work,text=True,capture_output=True)
  if c.returncode: raise CompositionError("static plugin configure failed",[ValidationError("configure","failed",(c.stdout+c.stderr)[-4000:])])
  b=subprocess.run([ninja],cwd=work,text=True,capture_output=True)
  if b.returncode: raise CompositionError("static plugin build failed",[ValidationError("ninja","failed",(b.stdout+b.stderr)[-4000:])])
  dol=work/builddir/"GALE01/main.dol"
  if not dol.is_file(): raise CompositionError("static build produced no main.dol")
  shutil.copy2(dol,output); return StaticBuildResult(output,_sha1(output),None,None)
 finally:
  subprocess.run(["git","worktree","remove","--force",str(work)],cwd=repo,capture_output=True,text=True)
  shutil.rmtree(temp,ignore_errors=True)
