"""Build Pascal UI from design/tokens.json and copy it to every surface that uses it.

    python design/build.py            # writes design/dist/*
    python design/build.py --sync     # ...and copies pascal-ui.css into the app, Studio and website

Outputs:
    dist/tokens.css      CSS custom properties (--pp-*), dark by default, light on [data-theme=light]
    dist/pascal-ui.css   tokens.css + components.css: the one stylesheet a page links
    dist/pascal_theme.h  ImGui style for the in-game F2 overlay (PascalUI::Apply)
    dist/tokens.py       the same values for Python tooling (Tk fallbacks, generators)
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DIST = HERE / "dist"
# Where --sync copies pascal-ui.css. Paths outside this repo are skipped when absent.
CONSUMERS = [
    REPO / "host/src/pascalpatch/app/web/pascal-ui.css",
    REPO / "website/assets/pascal-ui.css",
    REPO.parent / "MeleeCharacterStudio/core/src/melee_character_studio/web/pascal-ui.css",
]


def _font(stack):
    return ", ".join(f'"{f}"' if " " in f else f for f in stack)


def _theme_vars(theme):
    out = [f"  --pp-{k.replace('_', '-')}: {v};" for k, v in theme.items()]
    grid = "rgba(120,140,255,0.06)" if theme["bg"].upper() < "#8" else "rgba(40,60,140,0.06)"
    out.append(f"  --pp-grid: {grid};")
    return out


def tokens_css(t):
    lines = [f"/* Pascal UI {t['version']} tokens. Generated by design/build.py from tokens.json; do not edit. */", ":root {"]
    lines += [f"  --pp-font-display: {_font(t['font']['display'])};",
              f"  --pp-font-body: {_font(t['font']['body'])};",
              f"  --pp-font-mono: {_font(t['font']['mono'])};",
              f"  --pp-tracking-display: {t['font']['tracking_display']};"]
    lines += [f"  --pp-size-{k}: {v}px;" for k, v in t["font"]["size"].items()]
    lines += [f"  --pp-space-{k}: {v}px;" for k, v in t["space"].items()]
    lines += [f"  --pp-radius-{k}: {v}px;" for k, v in t["radius"].items()]
    lines += [f"  --pp-slant-deg: {t['slant']['deg']}deg;", f"  --pp-slant-px: {t['slant']['px']}px;",
              f"  --pp-fast: {t['motion']['fast']};", f"  --pp-base: {t['motion']['base']};", f"  --pp-ease: {t['motion']['ease']};"]
    lines += [f"  --pp-{k}: {v};" for k, v in t["port"].items()]
    lines += ["  color-scheme: dark;"] + _theme_vars(t["theme"]["dark"]) + ["}"]
    lines += [':root[data-theme="light"] {', "  color-scheme: light;"] + _theme_vars(t["theme"]["light"]) + ["}"]
    return "\n".join(lines) + "\n"


def _rgba(hex_or_rgba, alpha=None):
    s = hex_or_rgba.strip()
    if s.startswith("rgba"):
        r, g, b, a = [float(x) for x in s[5:-1].split(",")]
        r, g, b = r / 255, g / 255, b / 255
    else:
        s = s.lstrip("#"); r, g, b = (int(s[i:i + 2], 16) / 255 for i in (0, 2, 4)); a = 1.0
    if alpha is not None:
        a = alpha
    return f"ImVec4({r:.3f}f, {g:.3f}f, {b:.3f}f, {a:.3f}f)"


def imgui_header(t):
    d = t["theme"]["dark"]
    col = {
        "Text": _rgba(d["text"]), "TextDisabled": _rgba(d["text_dim"]),
        "WindowBg": _rgba(d["panel"], 0.96), "ChildBg": _rgba(d["sunken"], 0.6), "PopupBg": _rgba(d["raised"], 0.98),
        "Border": _rgba(d["line_strong"]), "BorderShadow": _rgba(d["bg"], 0.0),
        "FrameBg": _rgba(d["sunken"]), "FrameBgHovered": _rgba(d["raised"]), "FrameBgActive": _rgba(d["line"]),
        "TitleBg": _rgba(d["raised"]), "TitleBgActive": _rgba(d["raised"]), "TitleBgCollapsed": _rgba(d["panel"], 0.8),
        "MenuBarBg": _rgba(d["raised"]),
        "ScrollbarBg": _rgba(d["sunken"], 0.6), "ScrollbarGrab": _rgba(d["line"]), "ScrollbarGrabHovered": _rgba(d["line_strong"]), "ScrollbarGrabActive": _rgba(d["accent"]),
        "CheckMark": _rgba(d["accent"]), "SliderGrab": _rgba(d["accent"]), "SliderGrabActive": _rgba(d["accent_hover"]),
        "Button": _rgba(d["raised"]), "ButtonHovered": _rgba(d["line_strong"]), "ButtonActive": _rgba(d["accent"], 0.85),
        "Header": _rgba(d["accent"], 0.30), "HeaderHovered": _rgba(d["accent"], 0.45), "HeaderActive": _rgba(d["accent"], 0.65),
        "Separator": _rgba(d["line"]), "SeparatorHovered": _rgba(d["line_strong"]), "SeparatorActive": _rgba(d["accent"]),
        "ResizeGrip": _rgba(d["line"], 0.5), "ResizeGripHovered": _rgba(d["line_strong"]), "ResizeGripActive": _rgba(d["accent"]),
        "Tab": _rgba(d["sunken"]), "TabHovered": _rgba(d["line_strong"]),
        "PlotLines": _rgba(d["info"]), "PlotHistogram": _rgba(d["accent"]),
        "TextSelectedBg": _rgba(d["accent"], 0.35), "NavCursor": _rgba(d["focus"]),
        "ModalWindowDimBg": _rgba("#030612", 0.6),
    }
    sets = "\n".join(f"    c[ImGuiCol_{k}] = {v};" for k, v in col.items())
    ports = ", ".join(_rgba(t["port"][p]) for p in ("p1", "p2", "p3", "p4"))
    return f"""// Pascal UI {t['version']} for Dear ImGui (the PascalPatch F2 overlay).
// Generated by design/build.py from design/tokens.json; do not edit.
#pragma once
#include "imgui.h"

namespace PascalUI {{

// Colours a plugin can use for its own widgets, matching the web surfaces.
inline ImVec4 Accent() {{ return {_rgba(d['accent'])}; }}
inline ImVec4 AccentText() {{ return {_rgba(d['accent_text'])}; }}
inline ImVec4 Highlight() {{ return {_rgba(d['highlight'])}; }}
inline ImVec4 Danger() {{ return {_rgba(d['danger'])}; }}
inline ImVec4 Ok() {{ return {_rgba(d['ok'])}; }}
inline ImVec4 Muted() {{ return {_rgba(d['text_muted'])}; }}
inline ImVec4 Port(int p) {{ static const ImVec4 k[4] = {{{ports}}}; return k[(p < 0 ? 0 : p > 3 ? 3 : p)]; }}

inline void Apply(ImGuiStyle& s = ImGui::GetStyle()) {{
    s.WindowPadding = ImVec2(14, 12);
    s.FramePadding = ImVec2(10, 6);
    s.ItemSpacing = ImVec2(10, 7);
    s.ItemInnerSpacing = ImVec2(8, 6);
    s.ScrollbarSize = 12;
    s.GrabMinSize = 12;
    s.WindowBorderSize = 2;
    s.FrameBorderSize = 0;
    s.TabBorderSize = 0;
    s.WindowRounding = 12;     // Melee's rounded menu frame
    s.ChildRounding = {t['radius']['lg']};
    s.FrameRounding = {t['radius']['md']};
    s.PopupRounding = {t['radius']['lg']};
    s.ScrollbarRounding = {t['radius']['sm']};
    s.GrabRounding = {t['radius']['sm']};
    s.TabRounding = {t['radius']['md']};
    s.WindowTitleAlign = ImVec2(0.02f, 0.5f);
    ImVec4* c = s.Colors;
{sets}
    c[ImGuiCol_TabSelected] = {_rgba(d['accent'])};
    c[ImGuiCol_TabSelectedOverline] = {_rgba(d['accent_hover'])};
    c[ImGuiCol_TabDimmed] = {_rgba(d['sunken'])};
    c[ImGuiCol_TabDimmedSelected] = {_rgba(d['line_strong'])};
}}

}}  // namespace PascalUI
"""


def tokens_py(t):
    return ("# Pascal UI tokens for Python tooling. Generated by design/build.py; do not edit.\n"
            f"TOKENS = {json.dumps({k: v for k, v in t.items() if not k.startswith('$')}, indent=1)}\n"
            "DARK = TOKENS['theme']['dark']\nLIGHT = TOKENS['theme']['light']\nPORTS = TOKENS['port']\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--sync", action="store_true", help="copy pascal-ui.css to the app, Studio and website")
    a = ap.parse_args(argv)
    t = json.loads((HERE / "tokens.json").read_text(encoding="utf-8"))
    DIST.mkdir(exist_ok=True)
    tcss = tokens_css(t)
    (DIST / "tokens.css").write_text(tcss, encoding="utf-8")
    ui = tcss + "\n" + (HERE / "components.css").read_text(encoding="utf-8")
    (DIST / "pascal-ui.css").write_text(ui, encoding="utf-8")
    (DIST / "pascal_theme.h").write_text(imgui_header(t), encoding="utf-8")
    (DIST / "tokens.py").write_text(tokens_py(t), encoding="utf-8")
    print("built", ", ".join(p.name for p in sorted(DIST.iterdir())))
    if a.sync:
        for dest in CONSUMERS:
            if dest.parent.is_dir():
                shutil.copy2(DIST / "pascal-ui.css", dest); print("synced", dest)
            else:
                print("skipped (no folder)", dest.parent)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
